// <auto-generated />
using System;
using MakaleSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakaleSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250317151512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MakaleSistemi.Models.Makale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TakipNumarasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YazarEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Makaleler");
                });
#pragma warning restore 612, 618
        }
    }
}
