// <auto-generated />
using System;
using MakaleSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakaleSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250326154806_MakeYorumNullable")]
    partial class MakeYorumNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MakaleSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MakaleSistemi.Models.LogKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MakaleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("MakaleId");

                    b.ToTable("LogKayitlari");
                });

            modelBuilder.Entity("MakaleSistemi.Models.Makale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TakipNumarasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YazarEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Makaleler");
                });

            modelBuilder.Entity("MakaleSistemi.Models.MakaleHakem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HakemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MakaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yorum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MakaleId");

                    b.ToTable("MakaleHakemler");
                });

            modelBuilder.Entity("MakaleSistemi.Models.Mesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliciEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GonderenEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mesajlar");
                });

            modelBuilder.Entity("MakaleSistemi.Models.LogKayit", b =>
                {
                    b.HasOne("MakaleSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakaleSistemi.Models.Makale", "Makale")
                        .WithMany()
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("MakaleSistemi.Models.MakaleHakem", b =>
                {
                    b.HasOne("MakaleSistemi.Models.Makale", "Makale")
                        .WithMany()
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makale");
                });
#pragma warning restore 612, 618
        }
    }
}
